### ISSUE TITLE
Не выгружаются сохраненные материалы!!!

### ISSUE THREAD

**Issue by maxim1967** [Korchy/BIS#1]
Не могу обратно загрузить сохраненный на BIS материал!!! Материал отображается но не загружается в блендер.
Блендер 2.90.1, BIS последняя версия 1.9.0

**Comment by Korchy** [comment]
Сейчас проводится преобразование формата хранения данных по материалам в базе, поэтому возможны проблемы в работе аддона.
В первую очередь попробуйте перекачать аддон и переустановить его, я вносил некоторые правки внутри текущей версии 1.9.0.

**Comment by maxim1967** [comment]
Не помогло переустановил из репозитория BIS-master.zip. Может что не так сохранилось, не грузятся только мои сохраненные материалы. Сможете проверить материал "Gold Yellow 750 MRE" в открытом доступе.

**Comment by Korchy** [comment]
Похоже я нашел ошибку. Перекачайте еще раз аддон и прееустановите его. Я внес изменения в аддон и в ваш материал, сейчас он должен корректно грузиться.
Еще несколько дней, пока идут работы по обновлению формата, будьте осторожны с сохранением материалов, на всякий случай делайте резервную копию у себя на диске. При масштабной доработке аддона всегда возможно появлиени ошибки.

**Comment by maxim1967** [comment]
![Oschibka-001](https://user-images.githubusercontent.com/62519357/96689827-979d9180-138b-11eb-8cfb-a743a87f9d10.JPG)
Теперь на оборот загрузить не могу. С выгрузкой теперь нормально, выгружаются.

**Comment by Korchy** [comment]
Можете выложить blend-файл с материалом на какой-нибудь файлобменник, чтобы я мог посмотреть его. Мне не удается воспроизвести проблему при сохранении.

**Comment by maxim1967** [comment]
https://yadi.sk/d/84U0OMGwqCKR6w  Вот пожалуйста посмотрите

**Comment by Korchy** [comment]
Перекачайте и переустановите аддон, и попробуйте сохранить/загрузить этот материал.

**Comment by maxim1967** [comment]
Не не грузится. Я думаю что проблема в этом материале, он содержит другую нодовую группу и и конфликт именно с ней. Но мы не будем больше мучить этот материал, все равно я нашел ему альтернативу причем более качественную. Ваш "Dispersion glass" и мои настройки получился не плохой "Dispersion glass (Diamond)", а если еще повозится с ним мы можем получить и "Муассанит", и "Мистик", возможно и еще чтонибуть. Да я доработал ваш "Malachite" внем несколько не правильная гамма была и вы его слишком намельчили теперь есть "Malachite 2".

**Comment by Korchy** [comment]
Я боюсь, раз не найден источник проблемы, она может вылезти в каком-нибудь другом материале. У меня ваш материал корректно сохраняется и загружается. Судя по скриншоту ошибки у нода Reroute у вас появляется какое-то новое свойтсво "absolute location". Возможно его добавляет какой-то другой аддон для каких-то своих нужд. А BIS не может его обработать т.к. оно не базовое. Видимо мне пока не удается подобрать правильное условие чтобы BIS не сохранял подобные сторонние свойства.

**Comment by maxim1967** [comment]
Все таки я был прав, нода Reroute находилась в другой нодовой группе которая была включена в этот материал как только я отсоединил ее все сразу сохранилось....
